---
# tasks file for roles/osp-instance-delete by Luis Pacheco
- name: Fetch Instance Info that are running
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: result

- debug:
   var: result
   verbosity: 2

- name: Delete instances
  os_server:
   cloud: ospcloud
   name: "{{ item.name }}"
   state: absent
  with_items: "{{result.ansible_facts.openstack_servers}}"
