---

- hosts: tag_instance_filter_three_tier_app_psrivast_redhat_com
  gather_facts: true
  roles:
  - name: osp-facts
# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: frontend
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appsdb
  roles:
    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}
