- hosts: frontends
  gather_facts: true
  tasks:
    - name: Curl website
      uri: url=http://frontend/ status_code=200
      delegate_to: localhost

    - name: Fail if 'Ansible has done its job' is not in the page content
      fail:
      when: "'Ansible has done its job' not in webpage.results[0].content"
      tags:
        - aws.smoke
