---

- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts
# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: frontend
  become: yes
  roles:
    - {name: three_tier_common, tags: base-config}
    - {name: three_tier_frontend, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: three_tier_common, tags: base-config}
    - {name: three_tier_app, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appsdb
  roles:
    - {name: three_tier_common, tags: base-config}
    - {name: three_tier_appdb, tags: [dbs, postgres]}
